# Copyright 2026 Jim Schubert
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Create Release
# See https://docs.github.com/en/actions/sharing-automations/creating-workflow-templates-for-your-organization
# See https://github.blog/developer-skills/github/using-reusable-workflows-github-actions/
# When a reusable workflow is triggered by a caller workflow, the github context is always associated with the caller workflow. The called workflow is automatically granted access to github.token and secrets.GITHUB_TOKEN.
on:
  workflow_call:
    inputs:
      changelog-config:
        description: 'Path to changelog config file'
        required: false
        type: string
        default: ".github/changelog.yml"

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-go-release
  cancel-in-progress: true

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Find Last Tag
        if: success()
        id: last
        continue-on-error: true
        uses: jimschubert/query-tag-action@v2
        with:
          include: 'v*'
          exclude: '*-rc*'
          commit-ish: 'HEAD~'
          skip-unshallow: 'true'

      - name: Find Current Tag
        if: success()
        id: current
        uses: jimschubert/query-tag-action@v2
        with:
          include: 'v*'
          exclude: '*-rc*'
          commit-ish: '@'
          skip-unshallow: 'true'

      - name: Create Changelog
        if: success() && steps.last.outcome == 'success'
        id: changelog
        uses: jimschubert/beast-changelog-action@v1
        with:
          CONFIG_LOCATION: ${{ inputs.changelog-config }}
          FROM: ${{ steps.last.outputs.tag }}
          TO: ${{ steps.current.outputs.tag }}

      - name: Find First Commit
        if: success() && steps.last.outcome != 'success'
        id: first-commit
        run: |
          FIRST_COMMIT=$(git rev-list --max-parents=0 HEAD | head -n 1)
          echo "sha=$FIRST_COMMIT" >> $GITHUB_OUTPUT

      - name: Create First Release Changelog
        if: success() && steps.last.outcome != 'success'
        id: changelog-first
        uses: jimschubert/beast-changelog-action@v1
        with:
          CONFIG_LOCATION: ${{ inputs.changelog-config }}
          FROM: ${{ steps.first-commit.outputs.sha }}
          TO: ${{ steps.current.outputs.tag }}

      - name: View Changelog
        run: cat .github/CHANGELOG.md

      - name: Create Release
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}/.github/CHANGELOG.md

      - name: Update pkg.go.dev
        if: success()
        run: |
          # Wait 1 minute to ensure proxy.golang.org is updated
          sleep 60
          curl https://proxy.golang.org/github.com/${{ github.repository }}/@v/${{ github.ref_name }}.info || echo "pkg.go.dev not updated"
